server:
  port: 8080

spring:
  application:
    name: stockguard
  mvc:
    servlet:
      path: /api

  profiles:
    active: ${ACTIVE_PROFILE}

app:
  encryption:
    key: ${ENCRYPTION_KEY:S3cr3tK3y1234567

logging:
  level:
    org:
      springframework: INFO