spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          # DeepSeek model via OpenRouter
          model: deepseek/deepseek-chat

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

